[package]
name = "project_unify"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssh2 = { version = "0.9.4" }
serde_json = "1.0"
logger = {path = "../logger"}
